[build-system]
requires = [
  "Cython",
  "numpy",
  "lisaanalysistools>=1.0.17",
  "scikit_build_core",
]
build-backend = "scikit_build_core.build"

[project]
name = "gbgpu"
version = "1.1.4"
description = "GPU/CPU Galactic Binary Waveforms"
license = "GPL-3.0-or-later"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
authors = [
  { name = "Michael Katz", email = "mikekatz04@gmail.com" },
]
readme = "README.md"

requires-python = ">= 3.9"
dependencies = [
  "requests",
  "numpy",
  "scipy",
  "matplotlib",
  "h5py",
  "lisaanalysistools>=1.0.17",
]

[project.optional-dependencies]
cuda11 = [
  "cupy-cuda11x"
]
cuda12 = [
  "cupy-cuda12x"
]
