[build-system]
requires = [
  "setuptools",
  "wheel",
  "Cython",
  "numpy",
  "lisaanalysistools",
]
build-backend = 'setuptools.build_meta'

[project]
name = "gbgpu"
version = "1.1.3"
description = "GPU/CPU Galactic Binary Waveforms"
license = "GPL-3.0-or-later"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
authors = [
  { name = "Michael Katz", email = "mikekatz04@gmail.com" },
]
readme = "README.md"

requires-python = ">= 3.12"
dependencies = [
  "requests",
  "numpy",
  "scipy",
  "matplotlib",
  "h5py",
  "lisaanalysistools",
]

[project.optional-dependencies]
cuda11 = [
  "cupy-cuda11x"
]
cuda12 = [
  "cupy-cuda12x"
]